version: '3.4'

services:
  musicforum:
    image: musicforum
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file:
      - .env
    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: music_forum
      DB_HOST: mysql
      DB_PORT: $MYSQLDB_DOCKER_PORT
    ports:
      - 3000:3000
    depends_on:
      - mysql
  mysql:
    image: mysql:8.0.35
    restart: always
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: music_forum
    ports:
      # - "${MYSQLDB_LOCAL_PORT}:${MYSQLDB_DOCKER_PORT}"
      - 3306:3306
    volumes:
      - db_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    cap_add:
      - SYS_NICE  # CAP_SYS_NICE

volumes:
  db_data:
    driver: local